import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "globals.scss";
import { ReactNode } from "react";

const font = Roboto({
  weight: ["400", "500"],
  subsets: ["latin"],
  variable: "--font-roboto",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type Props = { children: ReactNode };
export default function RootLayout({ children }: Props) {
  return (
    <html className={font.className}>
      <body>{children}</body>
    </html>
  );
}
